"""Configuration for verifier nodes."""

from __future__ import annotations


MAX_SEARCH_QUERIES = 3
RANKER_HEURISTIC_TOP_N = 10
RANKER_LLM_TOP_K = 5
RANKER_HEURISTIC_FALLBACK_MIN_OVERLAP = 0.6
RANKER_MIN_SCORE = 0.4

QUERY_GEN_TEMPERATURE = 0.3
RANKER_TEMPERATURE = 0.0
VERDICT_TEMPERATURE = 0.0
