"""Configuration for verifier nodes."""

from __future__ import annotations


MAX_ITERATIONS = 3
QUERIES_PER_ITERATION = 1
MAX_SEARCH_QUERIES = QUERIES_PER_ITERATION
MAX_SNIPPET_WORDS = 150
MAX_EVIDENCE_TOKENS = 1200
QUERY_GEN_NUM_CTX = 2048
EVAL_NUM_CTX = 4096

RANKER_HEURISTIC_TOP_N = 10
RANKER_LLM_TOP_K = 5
RANKER_HEURISTIC_FALLBACK_MIN_OVERLAP = 0.6
RANKER_MIN_SCORE = 0.4

QUERY_GEN_TEMPERATURE = 0.0
RANKER_TEMPERATURE = 0.0
VERDICT_TEMPERATURE = 0.0
EVALUATOR_TEMPERATURE = 0.0
