"""Runtime tuning for the reporter agent."""

from __future__ import annotations


SUMMARY_TEMPERATURE = 0.1
SUMMARY_NUM_CTX = 2048
SUMMARY_MAX_PREDICT = 512

MAX_CLAIMS_IN_PROMPT = 10
MAX_CLAIM_TEXT_CHARS = 120
MAX_REASONING_CHARS = 120
MAX_INPUT_PREVIEW_CHARS = 500
MAX_SOURCE_SNIPPET_CHARS = 180
